_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 41
                - 49
                - 55
                - 63
            "2":
                - 1
                - 41
                - 49
                - 55
                - 63
            "3":
                - 13
                - 14
                - 23
                - 55
                - 61
            "4": 3.8.20
            "5": 0.19.7
            "8":
                - 6
            "12": 0.19.7
            "13": linux-x86_64
act_layer:
    value: gelu
add_velocity:
    value: false
attn_drop:
    value: 0
batch_size:
    value: 16
data_root:
    value: data/motion3d/
data_root_2d:
    value: data/motion2d/
dim_feat:
    value: 64
dim_in:
    value: 3
dim_out:
    value: 3
dim_rep:
    value: 512
drop:
    value: 0
drop_path:
    value: 0
dt_file:
    value: h36m_sh_conf_cam_source_final.pkl
epochs:
    value: 60
flip:
    value: true
graph_only:
    value: false
hierarchical:
    value: false
installed_packages:
    value:
        GitPython: 3.1.44
        MarkupSafe: 2.1.5
        PyWavelets: 1.4.1
        PyYAML: 6.0.2
        annotated-types: 0.7.0
        asttokens: 3.0.0
        autocommand: 2.2.2
        backcall: 0.2.0
        backports.tarfile: 1.2.0
        certifi: 2025.1.31
        charset-normalizer: 3.4.1
        click: 8.1.8
        contourpy: 1.1.1
        cycler: 0.12.1
        decorator: 5.1.1
        docker-pycreds: 0.4.0
        easydict: "1.13"
        einops: 0.8.1
        eval-type-backport: 0.2.2
        executing: 2.2.0
        filelock: 3.16.1
        filterpy: 1.4.5
        fonttools: 4.56.0
        fsspec: 2025.2.0
        gitdb: 4.0.12
        huggingface-hub: 0.29.1
        idna: "3.10"
        imageio: 2.35.1
        importlib-metadata: 8.5.0
        importlib-resources: 6.4.5
        inflect: 7.3.1
        ipython: 8.12.3
        jaraco.collections: 5.1.0
        jaraco.context: 5.3.0
        jaraco.functools: 4.0.1
        jaraco.text: 3.12.1
        jedi: 0.19.2
        jinja2: 3.1.5
        kiwisolver: 1.4.7
        lazy-loader: "0.4"
        llvmlite: 0.41.1
        matplotlib: 3.7.1
        matplotlib-inline: 0.1.7
        more-itertools: 10.3.0
        mpmath: 1.3.0
        networkx: "3.1"
        numba: 0.58.1
        numpy: 1.24.4
        nvidia-cublas-cu12: 12.1.3.1
        nvidia-cuda-cupti-cu12: 12.1.105
        nvidia-cuda-nvrtc-cu12: 12.1.105
        nvidia-cuda-runtime-cu12: 12.1.105
        nvidia-cudnn-cu12: 9.1.0.70
        nvidia-cufft-cu12: 11.0.2.54
        nvidia-curand-cu12: 10.3.2.106
        nvidia-cusolver-cu12: 11.4.5.107
        nvidia-cusparse-cu12: 12.1.0.106
        nvidia-nccl-cu12: 2.20.5
        nvidia-nvjitlink-cu12: 12.8.61
        nvidia-nvtx-cu12: 12.1.105
        opencv-python: 4.11.0.86
        packaging: "24.2"
        parso: 0.8.4
        pexpect: 4.9.0
        pickleshare: 0.7.5
        pillow: 10.4.0
        pip: "24.2"
        platformdirs: 4.3.6
        prompt-toolkit: 3.0.50
        protobuf: 5.29.3
        psutil: 7.0.0
        ptyprocess: 0.7.0
        pure-eval: 0.2.3
        pydantic: 2.10.6
        pydantic-core: 2.27.2
        pygments: 2.19.1
        pyparsing: 3.1.4
        python-dateutil: 2.9.0.post0
        pytorch-wavelets: 1.3.0
        requests: 2.32.3
        safetensors: 0.5.2
        scikit-image: 0.21.0
        scipy: 1.10.1
        sentry-sdk: 2.22.0
        setproctitle: 1.3.5
        setuptools: 75.1.0
        six: 1.17.0
        smmap: 5.0.2
        stack-data: 0.6.3
        sympy: 1.13.3
        tifffile: 2023.7.10
        timm: 1.0.14
        tomli: 2.0.1
        torch: 2.4.1
        torchvision: 0.19.1
        tqdm: 4.67.1
        traitlets: 5.14.3
        triton: 3.0.0
        typeguard: 4.3.0
        typing-extensions: 4.12.2
        urllib3: 2.2.3
        wandb: 0.19.7
        wcwidth: 0.2.13
        wheel: 0.44.0
        yacs: 0.1.8
        zipp: 3.20.2
lambda_3d_velocity:
    value: 20
lambda_a:
    value: 0
lambda_av:
    value: 0
lambda_lg:
    value: 0
lambda_lv:
    value: 0
lambda_scale:
    value: 0.5
layer_scale_init_value:
    value: 1e-05
learning_rate:
    value: 0.0005
lr_decay:
    value: 0.99
mlp_ratio:
    value: 4
model_name:
    value: MotionAGFormer
n_frames:
    value: 81
n_layers:
    value: 26
name:
    value: MotionAGFormer-small
neighbour_num:
    value: 2
num_heads:
    value: 8
num_joints:
    value: 17
qkv_bias:
    value: false
qkv_scale:
    value: null
root_rel:
    value: true
run_id:
    value: os1s4pii
subset_list:
    value:
        - H36M-81
temporal_connection_len:
    value: 1
use_adaptive_fusion:
    value: true
use_layer_scale:
    value: true
use_proj_as_2d:
    value: false
use_tcn:
    value: false
use_temporal_similarity:
    value: true
weight_decay:
    value: 0.01
